name: "Unit Testing"
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y python3-mysql.connector python3-requests
      - run: python3 -m unittest
